language: ruby
before_install: gem update bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head
  - jruby
  - jruby-head
gemfile:
  - gemfiles/mongoid_3.gemfile
  - gemfiles/mongoid_4.gemfile
  - gemfiles/mongoid_5.gemfile
  - gemfiles/mongoid_6.gemfile
services:
  - mongodb
sudo: false